### PR TITLE
Fix Ink Console not appearing

### LINKED ISSUE #93: Console doesn't open on Atom
Atom's version is 0.4.1, Ink's version is 0.11.0,  Chlorine is 0.1.11

When connecting to Socket REPL, the console does not open.

### PR DESCRIPTION
**Pull request by mauricioszabo**
Fixes #93

### CODE REVIEW

File: src/chlorine/repl.cljs [hunk 1]
```diff
@@ -29,9 +29,10 @@
   (atom/info "Disconnected from REPLs" ""))
 
 (declare evaluate-top-block! evaluate-selection!)
-(def ^:private old-commands
+(defonce ^:private old-commands
   {:disconnect connection/disconnect!
    :evaluate-top-block evaluate-top-block!
+   :evaluate-block evaluate-top-block!
```
Comment (seancorfield) [inline src/chlorine/repl.cljs]: Should this map to `evaluate-block!` instead of `evaluate-top-block!`?

Comment (mauricioszabo) [reply src/chlorine/repl.cljs]: Yes, it should. Good catch, I'll change it.
